#define PLOOPY_DRAGSCROLL_MOMENTARY
#define PLOOPY_DRAGSCROLL_INVERT
#define PLOOPY_DRAGSCROLL_DIVISOR_H 16.0
#define PLOOPY_DRAGSCROLL_DIVISOR_V 8.0
#define PLOOPY_DPI_OPTIONS { 400, 1200 }
#define PLOOPY_DPI_DEFAULT 1
